/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OtherMyComponent {
    }
}
declare global {
    interface HTMLOtherMyComponentElement extends Components.OtherMyComponent, HTMLStencilElement {
    }
    var HTMLOtherMyComponentElement: {
        prototype: HTMLOtherMyComponentElement;
        new (): HTMLOtherMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "other-my-component": HTMLOtherMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface OtherMyComponent {
    }
    interface IntrinsicElements {
        "other-my-component": OtherMyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "other-my-component": LocalJSX.OtherMyComponent & JSXBase.HTMLAttributes<HTMLOtherMyComponentElement>;
        }
    }
}
